export const AVATAR_PRESETS = [
  { id: '1', icon: 'user', iconColor: '#2A3036', bg: '#EDEFF0', label: 'Auditor' },
  { id: '2', icon: 'eye', iconColor: '#1E5E3C', bg: '#EDF5F0', label: 'Argus Eye' },
  { id: '3', icon: 'shield', iconColor: '#2B4C7E', bg: '#EBF3FB', label: 'Guardian' },
  { id: '4', icon: 'award', iconColor: '#8C6D1F', bg: '#FAF3D7', label: 'Legal' },
  { id: '5', icon: 'briefcase', iconColor: '#8B2C2C', bg: '#FBE4E4', label: 'Civic Lead' },
  { id: '6', icon: 'search', iconColor: '#5C3882', bg: '#F2E8FA', label: 'Inspector' },
];

export const BANNER_THEMES = [
  { id: 'civicGreen', label: 'Civic Green', primary: '#1E5E3C', accent: '#268755' },
  { id: 'slateNavy', label: 'Slate Navy', primary: '#1F2E3D', accent: '#3B536B' },
  { id: 'deepCharcoal', label: 'Charcoal', primary: '#22252A', accent: '#383D45' },
];

export const DEMO_ACCOUNTS = [
  {
    name: 'Champ Thanachoat',
    handle: 'Citizen Auditor #4081',
    ward: 'Ward 112 • Indiranagar, East Zone',
    address: '#42, 12th Main Road, HAL 2nd Stage',
    area: 'Indiranagar, Ward 112',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560038',
    email: 'champ.auditor@gmail.com',
    phone: '+91 98765 43210',
    avatarType: 'preset',
    avatarIcon: 'user',
    avatarIconColor: '#2A3036',
    avatarBg: '#EDEFF0',
    avatarUri: '',
    bannerTheme: 'civicGreen',
    auditsCount: 42,
    resolvedCount: 18,
    score: '98.4%',
    digiLockerVerified: true,
  },
  {
    name: 'Priya Sharma',
    handle: 'Civic Lead #1024',
    ward: 'Ward 88 • Koramangala, South Zone',
    address: '#108, 4th Cross, 5th Block',
    area: 'Koramangala, Ward 88',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560095',
    email: 'priya.sharma.civic@gov.in',
    phone: '+91 94455 66778',
    avatarType: 'preset',
    avatarIcon: 'briefcase',
    avatarIconColor: '#8B2C2C',
    avatarBg: '#FBE4E4',
    avatarUri: '',
    bannerTheme: 'slateNavy',
    auditsCount: 129,
    resolvedCount: 84,
    score: '99.1%',
    digiLockerVerified: true,
  },
];
